CREATE TABLE IF NOT EXISTS category(
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    parent_id TINYINT(3) UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    alias VARCHAR(255) NOT NULL,
    keywords VARCHAR(255) DEFAULT NULL,
    description VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;