CREATE TABLE IF NOT EXISTS posts(
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    category_id TINYINT(3) UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    alias VARCHAR(255) NOT NULL,
    img VARCHAR(255) DEFAULT 'no_image.jpg',
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    autor VARCHAR(255) DEFAULT 'Неизвестен',
    content TEXT DEFAULT NULL,
    status ENUM('0', '1') DEFAULT '1',
    keywords VARCHAR(255) DEFAULT NULL,
    description VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;